language: perl
perl:
   - 5.18
branch:
  only:
    - master
before_install:
   - export AUTOMATED_TESTING=1 PATH=$PATH:rakudo/install/bin
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - "git clone git://github.com/xenoterracide/rakudo.git"
   - "cd rakudo && git checkout topic/annotations"
   - "perl Configure.pl --gen-moar --gen-nqp --backends=moar"
   - "make && make install && cd .."
script:
   - ./rakudo/install/bin/perl6 -Ilib t/persistence.t
