language: perl
perl:
   - 5.18
branch:
  only:
    - master
before_install:
   - export AUTOMATED_TESTING=1 PATH=$PATH:rakudo/install/bin
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - "git clone git://github.com/rakudo/rakudo.git"
   - "cd rakudo && perl Configure.pl --gen-moar --gen-nqp --backends=moar"
   - "make && make install && cd .."
script:
   - 'rakudo/install/bin/perl6'
   - prove -exec 'rakudo/install/bin/perl6 -Ilib'
